### PR TITLE
Fix round-robin example.

### PR DESCRIPTION
**Pull request by fteychene**
Change Nginx conf to force reevaluation of server.
Add aliases on network docker-compose.

### CODE REVIEW

**Comment by FranckErnewein** [comment]
```
MacBook-Pro-de-Franck-2:docker-compose-scale-example franckernewein$ docker-compose up
ERROR: Validation failed in file './docker-compose.yml', reason(s):
services.mynodeapp.networks contains an invalid type, it should be an array
MacBook-Pro-de-Franck-2:docker-compose-scale-example franckernewein$ docker-compose -v
docker-compose version 1.6.0, build d99cad6
MacBook-Pro-de-Franck-2:docker-compose-scale-example franckernewein$ docker -v
Docker version 1.10.2, build c3959b1
```

What you wrote is clearly valid according to the recent documentation (https://docs.docker.com/compose/compose-file/#networks)
And I think my docker/docker-compose versions are good too...
I'll try to investigate what's happening

**Comment by FranckErnewein** [comment]
okay my bad, https://github.com/docker/compose/issues/3046

**Comment by FranckErnewein** [comment]
👏  👏 👏 
docker-compose upgraded
everything works perfectly 
thanks man !!

**Comment by fteychene** [comment]
It's so good when it works :)
The first time I played to scale up and down my app for 10min xD

**Pull request merged**
